version: '3'
services:
  caddy:
    image: caddy/caddy:2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl/ssl.key:/etc/ssl/private/ssl.key
      - ./ssl/ssl.crt:/etc/ssl/certs/ssl.crt
      - ./ssl/origin-pull-ca.pem:/etc/ssl/certs/origin-pull-ca.pem
    environment:
      ACME_AGREE: 'true'
    env_file:
      - nouseprod.env
    depends_on:
      - db
      - nouse
      - phpmyadmin
      - grafana
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb-thread-concurrency=0
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./docker/mysql:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_DATABASE=nouse
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=userDocker
      - MYSQL_PASSWORD=passDocker
      - MYSQL_ROOT_PASSWORD=rootPass
    env_file:
      - nouseprod.env
  nouse:
    image: index.docker.io/nouse/website:latest
    container_name: nouse-container
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=nouse
      - MYSQL_USER=userDocker
      - MYSQL_PASSWORD=passDocker
    env_file:
      - nouseprod.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_USER=userDocker
      - PMA_PASSWORD=passDocker
    restart: always
    depends_on:
      - db
    volumes:
      - /sessions
  compressor:
    image: nouse/image-compressor:latest
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=nouse
      - MYSQL_USER=userDocker
      - MYSQL_PASSWORD=passDocker
    env_file:
      - nouseprod.env
  mysql-backup:
     image: databack/mysql-backup:latest
     restart: unless-stopped
     container_name: mysql-backup
     environment:
       - DB_SERVER=db
       - DB_PORT=3306
       - DB_USER=root
       - DB_PASS=rootPass
       - DB_NAMES=nouse
       - DB_DUMP_FREQ=1440 #Daily
       - DB_DUMP_BEGIN=0230 #2:30am
       - COMPRESSION=gzip
       - NICE=true
     env_file:
       - nouseprod.env
     depends_on:
       - db
     volumes:
       - /etc/localtime:/etc/localtime:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - db
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,cloudflare-app
      - GF_INSTANCE_NAME=Nouse
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_PORT=3001
      - GF_SERVER_ENABLE_GZIP=true
      - GF_SNAPSHOTS_EXTERNAL_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_SIGNOUT_REDIRECT_URL="https://nouse.co.uk"
      - GF_SMTP_ENABLED=false
      - GF_LOG_LEVEL=critical
      - GF_ALERTING_ENABLED=false
      - GF_EXPLORE_ENABLED=false
      - GF_DATE_FORMATS_DEFAULT_TIMEZONE="Europe/London"
      - GF_EXPRESSIONS_ENABLED=false
  netdata:
    hostname: yusunouse01.york.ac.uk
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - PGID=120
    depends_on: #Relies on everything because it needs to start last in order to access details of docker containers
      - caddy
      - nouse
      - db
      - phpmyadmin
      - mysql-backup
      - compressor
    volumes:
      - ./docker/netdata/config:/etc/netdata:ro
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
volumes:
  netdatalib:
  netdatacache:
  caddy:
  db_data: { }
  grafana: